### PR TITLE
Add codified sample instructions

### PR DESCRIPTION
**Pull request by stewartshea**
Addresses #65 

This PR simply adds some steps in the readme on how to install and configure the datasource with code rather than manual steps.

### CODE REVIEW

**Comment by davideschiera** [comment]
Nice! Thanks for the help ;-)

**Comment by tcjn** [comment]
Hello @stewartshea 

Regarding #66. 
Currently I am trying to import dashboards from my SysDig instance but I am having such issue: 

`t=2021-09-20T09:35:01+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/2/ui/dashboards status=404 remote_addr= time_ms=28 size=81 referer=https://grafana.local/datasources/edit/QSG5vrSRT`

I am not sure whether is issue with plugin itself or the sysdig instance.

**Comment by stewartshea** [comment]
@tcjn 

It's been a while since I've looked at this integration, but I fired up a test environment to see what may have changed. 
What version of the plugin are you using? I installed the latest, v0.10, which appears to have the following changes: 
- importing dashboards no longer shows up
- the actual auth fails and you need to hard code the destination to us2.app.sysdig.com (instead of just app.sysdig.com). 

At least that was my experience. What I did notice in the docs is that they were deprecating some of the dashboard API's, so I wonder if this is also related to your issue. 

https://docs.sysdig.com/en/docs/developer-tools/working-with-dashboards/dashboard-apis/#dashboard-apis

**Comment by tcjn** [comment]
> @tcjn
> 
> It's been a while since I've looked at this integration, but I fired up a test environment to see what may have changed. What version of the plugin are you using? I installed the latest, v0.10, which appears to have the following changes:
> 
> * importing dashboards no longer shows up
> * the actual auth fails and you need to hard code the destination to us2.app.sysdig.com (instead of just app.sysdig.com).
> 
> At least that was my experience. What I did notice in the docs is that they were deprecating some of the dashboard API's, so I wonder if this is also related to your issue.
> 
> https://docs.sysdig.com/en/docs/developer-tools/working-with-dashboards/dashboard-apis/#dashboard-apis

I confirm, in v010 there is no option to import dashboards.

**Pull request merged**
